### ISSUE TITLE
The pytorch environment package cannot find.

### ISSUE THREAD

**Issue by James-FE** [zhangchbin/RCIL#11] opened 2023-05-09 12:33 UTC
Hi, Zhangchbin. Thank you for opensource this project. I meet a problem when I'm trying to set up the environment.  The conda source cannot find the proper pytorch package. I already tried many sources, but they can't work. Is there any other way I can set up the programming environment?

Collecting package metadata (repodata.json): /done
Solving environment: failed

ResolvePackageNotFound:
  - pytorch==1.3.1=py3.6_cuda10.1.243_cudnn7.6.3_0
  - torchvision==0.4.2=py36_cu101

**Comment by zhangchbin** [comment] 2023-05-10 04:06
hi, @GhostDragon124 
I have checked the pytorch pre-compiled package on https://download.pytorch.org/whl/cu100/torch_stable.html , and there is no torch1.3.1 version. You can try to compile the pytorch from source code.

**Comment by James-FE** [comment] 2023-08-22 12:51
Thank you for your response, I tried compiling the PyTorch from the source code, but it still doesn't work. I also tried the original PLOP method environment setup, but many packages were missing, and I failed to set it up. I wonder if there is any other way I can setup up a correct environment for RCIL method. Could you give me more advice?

**Comment by zhangchbin** [comment] 2023-10-25 05:43
Hi, @GhostDragon124 
We found that high version pytorch can not reach the supposed performance due to the bug caused by InplaceABNSync, which has been fixed in our latest commitment. You can refer to our latest news. Sorry for the inconvenience caused.

**Closed as completed** 2023-11-29 00:45 UTC
